server {
    listen 80;
    server_name localhost;

    # --- INI KUNCINYA ---
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    # --------------------

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache assets
    location /assets/ {
        # Jangan diulang root-nya kalau udah ada di atas, biar bersih
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}